#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

_fix_frequencies
_set_frequencies

# If encrypt doesn't exist, create it
if [ -z "${encrypt:-}" ]; then
    encrypt="$(grep "^encrypt=" "$install_dir/Backup_list.conf" | cut -d= -f2)"
    if [ "$encrypt" = true ]; then
        encrypt=1
    else
        encrypt=0
    fi
    ynh_app_setting_set --key="encrypt" --value="$encrypt"
fi

# If core_backup doesn't exist, create it
# FIXMEhelpers2.1: maybe replace with: ynh_app_setting_set_default --key=core_backup --value="$(grep "^ynh_core_backup=" "$install_dir/Backup_list.conf" | cut -d= -f2)"
if [ -z "${core_backup:-}" ]; then
    core_backup="$(grep "^ynh_core_backup=" "$install_dir/Backup_list.conf" | cut -d= -f2)"
    ynh_app_setting_set --key="core_backup" --value="$core_backup"
fi

# If apps_backup doesn't exist, create it
# FIXMEhelpers2.1: maybe replace with: ynh_app_setting_set_default --key=apps_backup --value="$(grep --count --max-count=1 "^ynh_app_backup=" "$install_dir/Backup_list.conf")"
if [ -z "${apps_backup:-}" ]; then
    apps_backup="$(grep --count --max-count=1 "^ynh_app_backup=" "$install_dir/Backup_list.conf")"
    ynh_app_setting_set --key="apps_backup" --value="$apps_backup"
fi

# If overwrite_cron doesn't exist, create it
# FIXMEhelpers2.1: maybe replace with: ynh_app_setting_set_default --key=overwrite_cron --value=1
if [ -z "${overwrite_cron:-}" ]; then
    overwrite_cron=1
    ynh_app_setting_set --key="overwrite_cron" --value="$overwrite_cron"
fi

# If admin_mail_html doesn't exist, create it
# FIXMEhelpers2.1: maybe replace with: ynh_app_setting_set_default --key=admin_mail_html --value=1
if [ -z "${admin_mail_html:-}" ]; then
    admin_mail_html=1
    ynh_app_setting_set --key="admin_mail_html" --value="$admin_mail_html"
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir" --full_replace --keep="passkey Backup_list.conf"

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R "root:root" "$install_dir"
#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# Use logrotate to manage app-specific logfile(s)
ynh_config_add_logrotate

if (( overwrite_cron == 1 )); then
    # Add Cron configuration file
    ynh_config_add --template="archivist.cron" --destination="/etc/cron.d/$app"
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
